apiVersion: v1
kind: Service
                  
metadata:
  name: nodeapp
        
spec:
  type: NodePort
  selector:
      env: stat
  ports:
    - nodePort: 32500
      port: 80
      targetPort: 8000
